# workflows.yaml
main:
  params: [input]  # Optional: pass data into the workflow if needed.
  steps:
    - init:
        assign:
          # Replace with your Cloud Run service URL ending with /simulate.
          - cloudRunUrl: ${sys.get_env("service_url")}
    - callCloudRun:
        try:
          call: http.post
          args:
            url: ${cloudRunUrl}
            auth:
              type: OIDC
            headers:
              Content-Type: "application/json"
            body: ${input}
          result: response
        retry: ${http.default_retry}
    - returnResult:
        return: ${response.body}
