services:
  api-full:
    image: ${REGION:-us-central1}-docker.pkg.dev/${PROJECT_ID}/${REPO:-api-v2}/policyengine-api-full:${TAG:-latest}
    build:
      context: ..
      dockerfile: projects/policyengine-api-full/Dockerfile
      platforms:
        - linux/amd64

  api-simulation:
    image: ${REGION:-us-central1}-docker.pkg.dev/${PROJECT_ID}/${REPO:-api-v2}/policyengine-api-simulation:${TAG:-latest}
    build:
      context: ..
      dockerfile: projects/policyengine-api-simulation/Dockerfile
      platforms:
        - linux/amd64

  api-tagger:
    image: ${REGION:-us-central1}-docker.pkg.dev/${PROJECT_ID}/${REPO:-api-v2}/policyengine-api-tagger:${TAG:-latest}
    build:
      context: ..
      dockerfile: projects/policyengine-api-tagger/Dockerfile
      platforms:
        - linux/amd64
