name: Deploy (beta)

on:
  pull_request:
    branches:
      - main

concurrency:
  group: deploy-main

jobs:
  build_beta:
    name: Build beta
    uses: ./.github/workflows/gcp-build.reusable.yml
    with:
      environment: beta
    secrets: inherit
  
  build_prod:
    name: Build production
    needs: [build_beta]
    uses: ./.github/workflows/gcp-build.reusable.yml
    with:
      environment: prod
    secrets: inherit
  
  deploy_beta:
    name: Deploy beta
    needs: [build_beta]
    uses: ./.github/workflows/gcp-deploy.reusable.yml
    with:
      environment: beta
    secrets: inherit
