name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-main

jobs:
  build_beta:
    name: Build beta
    uses: ./.github/workflows/gcp-build.reusable.yml
    with:
      environment: beta
    secrets: inherit
  
  build_prod:
    name: Build production
    needs: [build_beta]
    uses: ./.github/workflows/gcp-build.reusable.yml
    with:
      environment: prod
    secrets: inherit
  
  deploy_beta:
    name: Deploy beta
    needs: [build_beta]
    uses: ./.github/workflows/gcp-deploy.reusable.yml
    with:
      environment: beta
    secrets: inherit
  
  deploy_prod:
    name: Deploy production
    needs: [build_prod, deploy_beta]
    uses: ./.github/workflows/gcp-deploy.reusable.yml
    with:
      environment: prod
    secrets: inherit
  
  publish_clients:
    name: Publish API clients
    needs: [deploy_prod]
    uses: ./.github/workflows/publish-clients.reusable.yml
    with:
      environment: prod
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI }}
