name: Reusable publish clients workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'The environment that was deployed (e.g., beta, prod)'
    secrets:
      PYPI_TOKEN:
        required: true
        description: 'PyPI API token for publishing packages'

jobs:
  publish:
    name: Publish API clients
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Generate API clients
      run: |
        ./scripts/generate-clients.sh
    
    - name: Publish clients to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        ./scripts/publish-clients.sh